name: tool_bocs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.5+1
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_messaging: ^16.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  connectivity_plus: ^7.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  rename_app: ^1.6.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/playstore_icon.png"
  image_path: "assets/playstore_icon.png"

flutter:
  uses-material-design: true

 
  assets:
    - assets/
    - assets/icons/chat.svg
    - assets/icons/give.svg
    - assets/icons/take.svg
    - assets/icons/logout.svg
    - assets/icons/logout1.svg
  
